SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/****** Script for SelectTopNRows command from SSMS  ******/
ALTER view [AP_RES].[svAcademicPortal_Projects_Sel] as


SELECT PROJ.RESEARCHER_ID, RES.AURION_ID, RES.TITLE AS SALUTATION, RES.FIRST_NAME, RES.PREFERRED_NAME, RES.LAST_NAME, PROJ.TITLE AS TITLE, 
             PROJ.DETAILS, RES.DISPLAY_NAME, RES.USERNAME, RES.EMAIL, RES.TH_REUTERS_RESEARCHER_ID, RES.ESPACE_AUTHOR_ID, 
             RES.PHOTO_URL, RES.PHOTO_THUMBNAIL_URL, RES.SCHOOL_URL, RES.FACEBOOK_URL, RES.TWITTER_URL, RES.LINKEDIN_URL, 
             RES.IS_ACTIVE, RES.IS_UQ_EXPERT, RES.IS_APPROVED_UQ_EXPERT, RES.IS_UQ_EXPERT_MOBILE_PRIVATE, RES.UQ_EXPERT_MOBILE, 
             RES.UQ_EXPERT_CONFIRMED_AT, RES.AUTO_PROFILE, RES.UQ_EXPERT_HOME_PHONE, RES.MANUALLY_MODIFIED_AT, RES.ORCID, RES.SCOPUS_ID, 
             RES.GOOGLE_SCHOLAR_ID, RES.DELETED_AT, RES.RESEARCH_IMPACT, RES.RR_DISPLAY_NAME
FROM   AP_RES.PROJECTS PROJ
INNER JOIN
AP_RES.RESEARCHERS RES
ON PROJ.RESEARCHER_ID = RES.ID
GO
