SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER view [AUR].[svAurionOrgUnitsReportsToPosition] as 

with cte as (
SELECT T101F130_REPORTS_TO_POSITION, [Back to ToC] FROM DD.SupervisoryOrganisation a  
inner join AUR.T101_POSITION b on a.[Back to ToC] = CONCAT(b.T101F015_ORGANISATION_UNIT_NO, b.T101F005_POSITION_NO)

where Superior_Organization_ID like 'NEW%')

SELECT T101F015_ORGANISATION_UNIT_NO, T101F005_POSITION_NO, [Back to ToC] FROM AUR.T101_POSITION a, CTE
where a.T101F005_POSITION_NO = cte.T101F130_REPORTS_TO_POSITION
GO
