SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER view [AUR].[svAURION_OrgUnitMaxESSLevel_Sel] as
SELECT T101F015_ORGANISATION_UNIT_NO, MAX(T101F235_ESS_AUTHORITY_LEVEL) as AUTH_LEVEL from AUR.T101_POSITION T101
where T101F010_POSITION_STATUS = 'active'
group by T101F015_ORGANISATION_UNIT_NO
GO
