SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER view [AUR].[svAURION_ActiveOrgUnits] as 
SELECT T106F005_ORGANISATION_UNIT_NO, T106F065_ORGANISATION_DESC
FROM [AUR].[T106_ORGANISATION_UNITS] 
WHERE T106F010_ORG_UNIT_STATUS = 'ACTIVE';
GO
