SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ADDR].[ADDRESS_ALIAS_TYPE_AUT](
	[CODE] [nvarchar](50) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO
