SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ADDR].[ADDRESS](
	[BUILDING_NAME] [text] NULL,
	[LOT_NUMBER_PREFIX] [text] NULL,
	[LOT_NUMBER] [text] NULL,
	[LOT_NUMBER_SUFFIX] [text] NULL,
	[FLAT_TYPE] [nvarchar](50) NULL,
	[FLAT_NUMBER_PREFIX] [text] NULL,
	[FLAT_NUMBER] [text] NULL,
	[FLAT_NUMBER_SUFFIX] [text] NULL,
	[LEVEL_TYPE] [varchar](50) NULL,
	[LEVEL_NUMBER_PREFIX] [text] NULL,
	[LEVEL_NUMBER] [text] NULL,
	[LEVEL_NUMBER_SUFFIX] [text] NULL,
	[NUMBER_FIRST_PREFIX] [text] NULL,
	[NUMBER_FIRST] [text] NULL,
	[NUMBER_FIRST_SUFFIX] [text] NULL,
	[NUMBER_LAST_PREFIX] [text] NULL,
	[NUMBER_LAST] [text] NULL,
	[NUMBER_LAST_SUFFIX] [text] NULL,
	[STREET_NAME] [text] NULL,
	[STREET_CLASS_CODE] [text] NULL,
	[STREET_CLASS_TYPE] [nvarchar](50) NULL,
	[STREET_TYPE_CODE] [text] NULL,
	[STREET_SUFFIX_CODE] [text] NULL,
	[STREET_SUFFIX_TYPE] [nvarchar](50) NULL,
	[LOCALITY_NAME] [nvarchar](50) NULL,
	[STATE_ABBREVIATION] [varchar](3) NOT NULL,
	[POSTCODE] [int] NOT NULL,
	[LATITUDE] [float] NOT NULL,
	[LONGITUDE] [float] NOT NULL,
	[PRIMARY_SECONDARY] [text] NULL,
	[LEGAL_PARCEL_ID] [text] NULL,
	[DATE_CREATED] [datetime2](7) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
